import anthropic
import smtplib
import os
import markdown
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import date

TODAY = date.today().strftime("%B %d, %Y")

MODEL = "claude-opus-4-8"

# Web search is a server-side tool: Claude decides when to search, the API
# runs the query and hands results back to Claude, and this can repeat
# several times in one request before Claude writes the final brief.
WEB_SEARCH_TOOL = {"type": "web_search_20250305", "name": "web_search", "max_uses": 20}

PROMPT = f"""Produce a daily brief on AI monetization, value chain, and pricing news, covering a mix of business and technical topics.

Today's date is {TODAY}. Use the web search tool to find current news and analysis — do not rely on memory for anything time-sensitive, since prices, deals, and earnings figures change constantly. Search with varied, specific terms (e.g. "AI monetization news", "AI pricing model announcement", "AI value chain economics", "AI infrastructure margin", "enterprise AI ROI", "inference cost 2026") and include the current year in queries for recency. Run enough searches to cover all six sections below with real, dated news rather than generalities.

Structure the brief with these sections:
1. Headline roundup (3-5 items): latest news on AI pricing models, monetization announcements, earnings/margin commentary from major AI labs and infra providers.
2. Value chain spotlight: rotate through layers (compute/infra, model providers, platform/tooling, application layer, end-user/consumer), tracking where value and margin are concentrating.
3. Pricing model watch: usage-based vs. subscription vs. outcome-based vs. hybrid pricing trends; notable pricing changes from vendors (OpenAI, Anthropic, Google, Microsoft, etc.).
4. Business deep dive: one focused topic per day (e.g. unit economics of inference, enterprise AI ROI data, agentic pricing, API cost trends).
5. Technical deep dive: one focused topic per day (e.g. inference cost optimization, GPU/compute economics, model efficiency vs. pricing tradeoffs).
6. Quick links: 2-3 additional articles worth a skim.

Each section should include a 1-2 sentence summary followed by source links formatted as Markdown hyperlinks, e.g. [Title](URL). Keep the tone concise and direct, minimal fluff. Format the whole brief in Markdown, with a level-2 heading (##) per section."""

HTML_WRAPPER = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    font-size: 15px;
    line-height: 1.6;
    color: #1a1a1a;
    background-color: #f5f5f5;
    margin: 0;
    padding: 20px;
  }}
  .container {{
    max-width: 680px;
    margin: 0 auto;
    background: #ffffff;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 1px 4px rgba(0,0,0,0.08);
  }}
  .header {{
    background: #0f0f0f;
    color: #ffffff;
    padding: 28px 32px 24px;
  }}
  .header h1 {{
    margin: 0 0 4px;
    font-size: 20px;
    font-weight: 600;
    letter-spacing: -0.3px;
  }}
  .header .date {{
    color: #888888;
    font-size: 13px;
    margin: 0;
  }}
  .content {{
    padding: 28px 32px;
  }}
  h2 {{
    font-size: 13px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.8px;
    color: #666666;
    margin: 32px 0 12px;
    padding-bottom: 6px;
    border-bottom: 1px solid #eeeeee;
  }}
  h2:first-child {{
    margin-top: 0;
  }}
  h3 {{
    font-size: 15px;
    font-weight: 600;
    color: #1a1a1a;
    margin: 16px 0 4px;
  }}
  p {{
    margin: 0 0 12px;
    color: #333333;
  }}
  ul, ol {{
    padding-left: 20px;
    margin: 0 0 12px;
  }}
  li {{
    margin-bottom: 6px;
    color: #333333;
  }}
  a {{
    color: #0066cc;
    text-decoration: none;
  }}
  a:hover {{
    text-decoration: underline;
  }}
  strong {{
    font-weight: 600;
    color: #1a1a1a;
  }}
  code {{
    background: #f0f0f0;
    padding: 1px 5px;
    border-radius: 3px;
    font-size: 13px;
    font-family: 'SF Mono', 'Fira Code', monospace;
  }}
  blockquote {{
    border-left: 3px solid #dddddd;
    margin: 12px 0;
    padding: 4px 16px;
    color: #555555;
  }}
  .footer {{
    padding: 16px 32px;
    background: #f9f9f9;
    border-top: 1px solid #eeeeee;
    font-size: 12px;
    color: #999999;
    text-align: center;
  }}
</style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>AI Monetization Brief</h1>
      <p class="date">{date}</p>
    </div>
    <div class="content">
      {body}
    </div>
    <div class="footer">
      Generated by Claude &middot; {date}
    </div>
  </div>
</body>
</html>
"""


def generate_brief():
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    messages = [{"role": "user", "content": PROMPT}]

    response = client.messages.create(
        model=MODEL,
        max_tokens=4096,
        messages=messages,
        tools=[WEB_SEARCH_TOOL],
    )

    # Web search runs server-side and can loop through several searches within
    # one request. Very long research turns can come back with stop_reason
    # "pause_turn" instead of finishing — when that happens, send the paused
    # assistant turn back unchanged so Claude can keep going.
    while response.stop_reason == "pause_turn":
        messages.append({"role": "assistant", "content": response.content})
        response = client.messages.create(
            model=MODEL,
            max_tokens=4096,
            messages=messages,
            tools=[WEB_SEARCH_TOOL],
        )

    # The response interleaves text blocks with server_tool_use /
    # web_search_tool_result blocks; only the text blocks are the brief itself.
    return "\n\n".join(block.text for block in response.content if block.type == "text")


def markdown_to_html(md_text):
    """Convert Markdown to HTML using the markdown library."""
    body_html = markdown.markdown(
        md_text,
        extensions=["extra", "nl2br"]
    )
    return HTML_WRAPPER.format(date=TODAY, body=body_html)


def send_email(body_md):
    sender = os.environ["GMAIL_USER"]
    password = os.environ["GMAIL_APP_PASSWORD"]
    recipient = os.environ["GMAIL_USER"]

    body_html = markdown_to_html(body_md)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"AI Monetization Brief — {TODAY}"
    msg["From"] = sender
    msg["To"] = recipient

    # Plain text fallback first, HTML second (email clients prefer last part)
    msg.attach(MIMEText(body_md, "plain"))
    msg.attach(MIMEText(body_html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, recipient, msg.as_string())

    print("Email sent successfully.")


if __name__ == "__main__":
    print(f"GMAIL_USER: '{os.environ.get('GMAIL_USER', 'NOT SET')}'")
    print(f"APP_PASSWORD length: {len(os.environ.get('GMAIL_APP_PASSWORD', ''))}")
    print("Generating brief...")
    brief = generate_brief()
    print("Sending email...")
    send_email(brief)
