import anthropic
import smtplib
import os
import markdown
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import date

PROMPT = """Produce a daily brief on AI monetization, value chain, and pricing news, covering a mix of business and technical topics. Research using your knowledge and reasoning for current trends.
Structure the brief with these sections:
1. Headline roundup (3-5 items): latest news on AI pricing models, monetization announcements, earnings/margin commentary from major AI labs and infra providers.
2. Value chain spotlight: rotate through layers (compute/infra, model providers, platform/tooling, application layer, end-user/consumer), tracking where value and margin are concentrating.
3. Pricing model watch: usage-based vs. subscription vs. outcome-based vs. hybrid pricing trends; notable pricing changes from vendors (OpenAI, Anthropic, Google, Microsoft, etc.).
4. Business deep dive: one focused topic per day (e.g. unit economics of inference, enterprise AI ROI data, agentic pricing, API cost trends).
5. Technical deep dive: one focused topic per day (e.g. inference cost optimization, GPU/compute economics, model efficiency vs. pricing tradeoffs).
6. Quick links: 2-3 additional topics worth a skim.
Each section should include a 1-2 sentence summary. Keep the tone concise and direct, minimal fluff. Format in Markdown."""

HTML_WRAPPER = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    font-size: 15px;
    line-height: 1.6;
    color: #1a1a1a;
    background-color: #f5f5f5;
    margin: 0;
    padding: 20px;
  }}
  .container {{
    max-width: 680px;
    margin: 0 auto;
    background: #ffffff;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 1px 4px rgba(0,0,0,0.08);
  }}
  .header {{
    background: #0f0f0f;
    color: #ffffff;
    padding: 28px 32px 24px;
  }}
  .header h1 {{
    margin: 0 0 4px;
    font-size: 20px;
    font-weight: 600;
    letter-spacing: -0.3px;
  }}
  .header .date {{
    color: #888888;
    font-size: 13px;
    margin: 0;
  }}
  .content {{
    padding: 28px 32px;
  }}
  h2 {{
    font-size: 13px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.8px;
    color: #666666;
    margin: 32px 0 12px;
    padding-bottom: 6px;
    border-bottom: 1px solid #eeeeee;
  }}
  h2:first-child {{
    margin-top: 0;
  }}
  h3 {{
    font-size: 15px;
    font-weight: 600;
    color: #1a1a1a;
    margin: 16px 0 4px;
  }}
  p {{
    margin: 0 0 12px;
    color: #333333;
  }}
  ul, ol {{
    padding-left: 20px;
    margin: 0 0 12px;
  }}
  li {{
    margin-bottom: 6px;
    color: #333333;
  }}
  a {{
    color: #0066cc;
    text-decoration: none;
  }}
  a:hover {{
    text-decoration: underline;
  }}
  strong {{
    font-weight: 600;
    color: #1a1a1a;
  }}
  code {{
    background: #f0f0f0;
    padding: 1px 5px;
    border-radius: 3px;
    font-size: 13px;
    font-family: 'SF Mono', 'Fira Code', monospace;
  }}
  blockquote {{
    border-left: 3px solid #dddddd;
    margin: 12px 0;
    padding: 4px 16px;
    color: #555555;
  }}
  .footer {{
    padding: 16px 32px;
    background: #f9f9f9;
    border-top: 1px solid #eeeeee;
    font-size: 12px;
    color: #999999;
    text-align: center;
  }}
</style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>AI Monetization Brief</h1>
      <p class="date">{date}</p>
    </div>
    <div class="content">
      {body}
    </div>
    <div class="footer">
      Generated by Claude &middot; {date}
    </div>
  </div>
</body>
</html>
"""


def generate_brief():
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    message = client.messages.create(
        model="claude-opus-4-8",
        max_tokens=2048,
        messages=[{"role": "user", "content": PROMPT}]
    )
    return message.content[0].text


def markdown_to_html(md_text):
    """Convert Markdown to HTML using the markdown library."""
    body_html = markdown.markdown(
        md_text,
        extensions=["extra", "nl2br"]
    )
    today = date.today().strftime("%B %d, %Y")
    return HTML_WRAPPER.format(date=today, body=body_html)


def send_email(body_md):
    sender = os.environ["GMAIL_USER"]
    password = os.environ["GMAIL_APP_PASSWORD"]
    recipient = os.environ["GMAIL_USER"]

    today = date.today().strftime("%B %d, %Y")
    body_html = markdown_to_html(body_md)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"AI Monetization Brief — {today}"
    msg["From"] = sender
    msg["To"] = recipient

    # Plain text fallback first, HTML second (email clients prefer last part)
    msg.attach(MIMEText(body_md, "plain"))
    msg.attach(MIMEText(body_html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, recipient, msg.as_string())

    print("Email sent successfully.")


if __name__ == "__main__":
    print(f"GMAIL_USER: '{os.environ.get('GMAIL_USER', 'NOT SET')}'")
    print(f"APP_PASSWORD length: {len(os.environ.get('GMAIL_APP_PASSWORD', ''))}")
    print("Generating brief...")
    brief = generate_brief()
    print("Sending email...")
    send_email(brief)
